before:
  hooks:
    - go mod tidy
builds:
- 
  goos:
  - freebsd
  - netbsd
  - openbsd
  - dragonfly
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  - mips
  - mipsle
  - mips64
  - mips64le
  goarm:
  - 5
  - 6
  - 7
  gomips:
  - softfloat
  - hardfloat
  ignore:
  -
    goos: windows
    goarch: arm64
  env:
  - CGO_ENABLED=0
archives:
-
  format: binary
checksum:
  name_template: 'checksums.txt'
release:
  name_template: "{{.ProjectName}}-v{{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
